filter:
    excluded_paths:
        - Tests/*
build:
    tests:
        override:
            -
                command: 'vendor/bin/simple-phpunit --coverage-clover=clover-coverage.xml'
                coverage:
                    file: 'clover-coverage.xml'
                    format: 'clover'
